# Generated by Django 2.2.1 on 2019-05-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('rated', models.CharField(max_length=50)),
                ('released', models.DateField()),
                ('runtime', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('writer', models.TextField()),
                ('Actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('awards', models.TextField()),
                ('poster', models.URLField()),
                ('metascore', models.IntegerField()),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('imdb_votes', models.IntegerField()),
                ('imdbID', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('dvd_released', models.DateField()),
                ('box_office', models.IntegerField()),
                ('production', models.CharField(max_length=100)),
            ],
        ),
    ]
