# Generated by Django 2.2.1 on 2019-05-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='box_office',
            new_name='boxoffice',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='dvd_released',
            new_name='dvd',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='imdbID',
            new_name='imdbid',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_rating',
            new_name='imdbrating',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_votes',
            new_name='imdbvotes',
        ),
        migrations.AddField(
            model_name='movie',
            name='website',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
