# Generated by Django 2.2.1 on 2019-05-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0002_auto_20190525_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Actors',
            new_name='actors',
        ),
    ]
