# Generated by Django 2.2.1 on 2019-05-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0003_auto_20190525_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='dvd',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.DateField(null=True),
        ),
    ]
