# Generated by Django 2.2.1 on 2019-05-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0004_auto_20190525_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
