# Generated by Django 2.2.1 on 2019-05-26 04:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0008_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 26, 4, 47, 1, 327610, tzinfo=utc)),
        ),
    ]
