# Generated by Django 2.2.1 on 2019-05-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0010_auto_20190526_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='added_on',
        ),
    ]
