# Generated by Django 2.2.1 on 2019-05-26 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0011_auto_20190526_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added_on',
            field=models.DateField(default=datetime.date(2019, 5, 26)),
        ),
    ]
