# Generated by Django 2.2.1 on 2019-05-26 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0012_auto_20190526_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
